# Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Load Data

In [2]:
dataset = pd.read_csv("heart.csv")
dataset

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [3]:
dataset.isnull().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trtbps    303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalachh  303 non-null    int64  
 8   exng      303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64  
 11  caa       303 non-null    int64  
 12  thall     303 non-null    int64  
 13  output    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [5]:
dataset["thall"].unique()

array([1, 2, 3, 0])

In [6]:
dataset["slp"].unique()

array([0, 2, 1])

In [7]:
dataset["caa"].unique()

array([0, 2, 1, 3, 4])

# Encoding

**Columns to OneHotEncode are cp, restecg, slp, caa, thall**

In [8]:
cp = pd.get_dummies(dataset["cp"])
cp.columns = ["cp0", "cp1", "cp2", "cp3"]
restecg = pd.get_dummies(dataset["restecg"])
restecg.columns = ["recg0", "recg1", "recg2"]
slp = pd.get_dummies(dataset["slp"])
slp.columns = ["slp0", "slp1", "slp2"]
caa = pd.get_dummies(dataset["caa"])
caa.columns = ["caa0", "caa1", "caa2", "caa3", "caa4"]
thall = pd.get_dummies(dataset["thall"])
thall.columns = ["thall0", "thall1", "thall2", "thall3"]
dataset_final = pd.concat([dataset, cp, restecg, slp, caa, thall], axis=1)
dataset_final.drop(labels=["cp", "restecg", "slp", "caa", "thall"], axis=1, inplace=True)
dataset_final.head()

age  sex  trtbps  chol  fbs  thalachh  exng  oldpeak  output  cp0  ...  \
0   63    1     145   233    1       150     0      2.3       1    0  ...   
1   37    1     130   250    0       187     0      3.5       1    0  ...   
2   41    0     130   204    0       172     0      1.4       1    0  ...   
3   56    1     120   236    0       178     0      0.8       1    0  ...   
4   57    0     120   354    0       163     1      0.6       1    1  ...   

   slp2  caa0  caa1  caa2  caa3  caa4  thall0  thall1  thall2  thall3  
0     0     1     0     0     0     0       0       1       0       0  
1     0     1     0     0     0     0       0       0       1       0  
2     1     1     0     0     0     0       0       0       1       0  
3     1     1     0     0     0     0       0       0       1       0  
4     1     1     0     0     0     0       0       0       1       0  

[5 rows x 28 columns]

# Exporting data

In [9]:
# dataset_final.to_csv("heart_encoded.csv")